---
title: "DS4420 Final Project Bayesian Model"
author: "Sophia Yang, Veronica Song, Alina Gonzalez"
date: "2026-04-13"
output: pdf_document
---

# DS4420 Final Project Bayesian Model
### Sophia Yang, Veronica Song, Alina Gonzalez
## Objective 
We created a Bayesian predictive model that predicts the likelihood of pet adoption based on the animal’s identified key traits.

## Read Data
```{r read}
pets <- read.csv("pet_adoption_data.csv")
head(pets)
```

## Preprocess

```{r preprocess}
pets_scaled <- pets 

# numeric features get scaled
pets_scaled$AgeMonths <- as.numeric(scale(pets$AgeMonths))
pets_scaled$AdoptionFee <- as.numeric(scale(pets$AdoptionFee))
pets_scaled$WeightKg <- as.numeric(scale(pets$WeightKg))
pets_scaled$TimeInShelterDays <- as.numeric(scale(pets$TimeInShelterDays))

# categorical features
pets_scaled$Breed <- as.factor(pets$Breed)
pets_scaled$PetType <- as.factor(pets$PetType)
pets_scaled$HealthCondition <- as.factor(pets$HealthCondition)
pets_scaled$Vaccinated <- as.factor(pets$Vaccinated)
pets_scaled$PreviousOwner <- as.factor(pets$PreviousOwner)

# sanity check for Bernoulli outcome
stopifnot(all(pets_scaled$AdoptionLikelihood %in% c(0, 1)))
```

## Fit Bayes Model
```{r bayes model}
library(brms)

model <- brm(
  AdoptionLikelihood ~ AgeMonths + Breed + PetType + HealthCondition + Vaccinated +
    AdoptionFee + TimeInShelterDays + PreviousOwner + WeightKg,
  family = bernoulli("logit"),
  data = pets_scaled,
  chains = 4,
  cores = 4,
  seed = 42,
  warmup = 1000,
  iter = 2000,
  refresh = 100,
  control = list(adapt_delta = 0.95, max_treedepth = 12)
)
```

## Outcomes
lol uhh,,, are we supposed to do anythign else here....
```{r summary}
summary(model)
```
